import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar/page";
import HelmetWrapper from "@/providers/page";
import Footer from "./Footer/page";
import SessionWrapping from "@/lib/SessionWrapping";



const poppins = Poppins({
  subsets: ['latin'],
  weight: ['200', "400", "600", "800"]
})
export const metadata: Metadata = {
  title: "Nestify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapping>
      <html lang="en">
        <body

        >
          <HelmetWrapper>
            <div className={`${poppins.className} bg-white min-h-screen  text-black`}>
              <div>
                <Navbar />
              </div>
              {children}
              <div>
                <Footer />
              </div>
            </div>
          </HelmetWrapper>
        </body>
      </html>
    </SessionWrapping>
  );
}
