import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import HelmetWrapper from "@/providers/page";
import Footer from "./Footer/page";
import SessionWrapping from "@/lib/SessionWrapping";
import { Toaster } from "react-hot-toast";
import NavbarPage from "./NavbarPage/page";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['200', "400", "600", "800"]
});

export const metadata: Metadata = {
  title: "Nestify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapping>
      <Toaster />
      <html lang="en">
        <body>
          <HelmetWrapper>
            <div className={`${poppins.className} bg-white min-h-screen text-black`}>
              <NavbarPage />
              {children}
              <Footer />
            </div>
          </HelmetWrapper>
        </body>
      </html>
    </SessionWrapping>
  );
}
